spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lht_test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 198412

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
    timeout: 1000


server:
#  max-http-header-size: 655360
  port: 9090
mybatis:
    mapper-locations: classpath:mapper/*.xml
    config-location: classpath:mapper/mybatisConfig/mybatisConfig.xml
logging:
  config: classpath:logback-spring.xml








