spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.173:3306/quartz?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 198412

server:
  port: 8099
mybatis:
    mapper-locations: classpath:mapper/*.xml
    config-location: classpath:mapper/mybatisConfig/mybatisConfig.xml
logging:
  config: classpath:logback-spring.xml










