spring:
  datasource:
    master:
      url: jdbc:mysql://localhost:3306/lht_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 198412
      type: com.zaxxer.hikari.HikariDataSource
    cluster:
    - key: slave1
      url: jdbc:mysql://localhost:3306/lht_test1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 198412
      idle-timeout: 20000
      type: com.zaxxer.hikari.HikariDataSource
    - key: slave2
      url: jdbc:mysql://localhost:3306/lht_test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 198412
      idle-timeout: 20000
      type: com.zaxxer.hikari.HikariDataSource
  kafka:
    consumer:
      bootstrap-servers: 53.80.6.45:9092,53.80.6.46:9092,53.80.6.47:9092,53.80.6.48:9092
      enable-auto-commit: true
      auto-offset-reset: latest
      group-id: modi_g_1
    producer:
      bootstrap-servers: 53.80.6.45:9092,53.80.6.46:9092,53.80.6.47:9092,53.80.6.48:9092
      topic: modi
      acks: all
      retries: 0
      batch-size: 4096
      buffer-memory: 40960
      linger: 1
      client-id: socketClient

#server:
#  tomcat:
##  max-http-header-size: 655360
#  port: 9090

mybatis:
    mapper-locations: classpath:mapper/*.xml
    config-location: classpath:mapper/mybatisConfig/mybatisConfig.xml
logging:
  config: classpath:logback-spring.xml
JWT:
  header: Authorization
  secret: MasterSecret
  expiration: 10080
  tokenHead: "Bearer "


#httpclient配置参数
#最大连接数
http:
  maxTotal: 100
  #并发数
  defaultMaxPerRoute: 20
  #创建连接的最长时间
  connectTimeout: 10000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 5000
  #数据传输的最长时间
  socketTimeout: 100000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true








