spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/lht_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: 198412
  datasource:
    driverClassName: dm.jdbc.driver.DmDriver
    url: jdbc:dm://127.0.0.1:5236/DMSERVER?
    username: xuese1203
    password: lht025991
  kafka:
    consumer:
      bootstrap-servers: 47.110.8.129:9092
      enable-auto-commit: true
      auto-commit-interval: 1
      auto-offset-reset: latest
      group-id: jdbcstatus_1
    producer:
      bootstrap-servers: 47.110.8.129:9092
      topic: status-topic
      acks: all
      retries: 0
      batch-size: 4096
      buffer-memory: 40960
      linger: 1
      client-id: socketClient



server:
#  max-http-header-size: 655360
  port: 8066
mybatis:
    mapper-locations: classpath:mapper/*.xml
    config-location: classpath:mapper/mybatisConfig/mybatisConfig.xml
logging:
  config: classpath:logback-spring.xml










